"""initial schema

Revision ID: 43ccacb44d4a
Revises: 
Create Date: 2026-09-27 00:47:55.887252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43ccacb44d4a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('timeframe', sa.String(length=16), nullable=False),
    sa.Column('open_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('high', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('low', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('close', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('volume', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(
        'uq_candles_symbol_timeframe_open_time',
        'candles',
        ['symbol', 'timeframe', 'open_time'],
        unique=True,
    )
    op.create_table('heartbeats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service')
    )
    op.create_table('system_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('metadata', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('system_events', schema=None) as batch_op:
        batch_op.create_index('ix_system_events_created_at', ['created_at'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('ix_users_telegram_id', ['telegram_id'], unique=True)

    op.create_table('bot_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('execution_mode', sa.String(length=16), nullable=False),
    sa.Column('risk_profile', sa.String(length=16), nullable=False),
    sa.Column('enabled_symbols', sa.Text(), nullable=False),
    sa.Column('timeframe', sa.String(length=16), nullable=False),
    sa.Column('is_paused', sa.Boolean(), nullable=False),
    sa.Column('emergency_stop', sa.Boolean(), nullable=False),
    sa.Column('live_confirmed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('daily_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('trades_count', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('losses', sa.Integer(), nullable=False),
    sa.Column('gross_pnl', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('fees', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('net_pnl', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_daily_stats_user_id_date')
    )
    with op.batch_alter_table('daily_stats', schema=None) as batch_op:
        batch_op.create_index('ix_daily_stats_user_id_date', ['user_id', 'date'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=True),
    sa.Column('sent', sa.Boolean(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index('ix_notifications_user_id_sent', ['user_id', 'sent'], unique=False)

    op.create_table('strategies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('timeframe', sa.String(length=16), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('xrocket_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('encrypted_api_token', sa.Text(), nullable=True),
    sa.Column('environment', sa.String(length=16), nullable=False),
    sa.Column('is_connected', sa.Boolean(), nullable=False),
    sa.Column('last_balance_sync', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_ws_sync', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=True),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=36, scale=18), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=36, scale=18), nullable=True),
    sa.Column('stop_loss', sa.Numeric(precision=36, scale=18), nullable=True),
    sa.Column('take_profit', sa.Numeric(precision=36, scale=18), nullable=True),
    sa.Column('trailing_stop', sa.Numeric(precision=36, scale=18), nullable=True),
    sa.Column('peak_price', sa.Numeric(precision=36, scale=18), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.create_index('ix_positions_symbol_status', ['symbol', 'status'], unique=False)
        batch_op.create_index('ix_positions_user_id_status', ['user_id', 'status'], unique=False)

    op.create_table('strategy_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('ema_fast', sa.Integer(), nullable=False),
    sa.Column('ema_slow', sa.Integer(), nullable=False),
    sa.Column('rsi_period', sa.Integer(), nullable=False),
    sa.Column('atr_period', sa.Integer(), nullable=False),
    sa.Column('atr_sl_multiplier', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('take_profit_rr', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('trailing_activation_atr', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('trailing_atr_multiplier', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('min_volume_ratio', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('cooldown_minutes', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('strategy_id')
    )
    op.create_table('trade_signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=True),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('timeframe', sa.String(length=16), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('price', sa.Numeric(precision=36, scale=18), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trade_signals', schema=None) as batch_op:
        batch_op.create_index('ix_trade_signals_user_id_created_at', ['user_id', 'created_at'], unique=False)

    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=True),
    sa.Column('client_order_id', sa.String(length=64), nullable=False),
    sa.Column('xrocket_order_id', sa.String(length=64), nullable=True),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('order_type', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('price', sa.Numeric(precision=36, scale=18), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=36, scale=18), nullable=True),
    sa.Column('filled_quantity', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('average_price', sa.Numeric(precision=36, scale=18), nullable=True),
    sa.Column('fee', sa.Numeric(precision=36, scale=18), nullable=True),
    sa.Column('fee_asset', sa.String(length=16), nullable=True),
    sa.Column('time_in_force', sa.String(length=8), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index('ix_orders_client_order_id', ['client_order_id'], unique=True)
        batch_op.create_index('ix_orders_user_id_status', ['user_id', 'status'], unique=False)
        batch_op.create_index('ix_orders_xrocket_order_id', ['xrocket_order_id'], unique=False)

    op.create_table('trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=36, scale=18), nullable=True),
    sa.Column('entry_price', sa.Numeric(precision=36, scale=18), nullable=True),
    sa.Column('exit_price', sa.Numeric(precision=36, scale=18), nullable=True),
    sa.Column('gross_pnl', sa.Numeric(precision=36, scale=18), nullable=True),
    sa.Column('fees', sa.Numeric(precision=36, scale=18), nullable=True),
    sa.Column('net_pnl', sa.Numeric(precision=36, scale=18), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.create_index('ix_trades_user_id_closed_at', ['user_id', 'closed_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.drop_index('ix_trades_user_id_closed_at')

    op.drop_table('trades')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index('ix_orders_xrocket_order_id')
        batch_op.drop_index('ix_orders_user_id_status')
        batch_op.drop_index('ix_orders_client_order_id')

    op.drop_table('orders')
    with op.batch_alter_table('trade_signals', schema=None) as batch_op:
        batch_op.drop_index('ix_trade_signals_user_id_created_at')

    op.drop_table('trade_signals')
    op.drop_table('strategy_settings')
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.drop_index('ix_positions_user_id_status')
        batch_op.drop_index('ix_positions_symbol_status')

    op.drop_table('positions')
    op.drop_table('xrocket_accounts')
    op.drop_table('strategies')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index('ix_notifications_user_id_sent')

    op.drop_table('notifications')
    with op.batch_alter_table('daily_stats', schema=None) as batch_op:
        batch_op.drop_index('ix_daily_stats_user_id_date')

    op.drop_table('daily_stats')
    op.drop_table('bot_settings')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_telegram_id')

    op.drop_table('users')
    with op.batch_alter_table('system_events', schema=None) as batch_op:
        batch_op.drop_index('ix_system_events_created_at')

    op.drop_table('system_events')
    op.drop_table('heartbeats')
    op.drop_index('uq_candles_symbol_timeframe_open_time', table_name='candles')
    op.drop_table('candles')
    # ### end Alembic commands ###
